# Generated by Django 5.2.14 on 2026-08-04 13:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id_client", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=40)),
                ("client_phone_number", models.BigIntegerField()),
                ("client_email", models.CharField(max_length=100)),
                ("login_date", models.DateTimeField(auto_now_add=True)),
                ("numero_carte_credit", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("DEPOT", "Dépôt"),
                            ("RETRAIT", "Retrait"),
                            ("ASSISTANCE", "Assistance"),
                            ("CREATION_COMPTE", "Creation_compte"),
                            ("SERVICE_CLIENT", "Service_client"),
                        ],
                        max_length=50,
                    ),
                ),
                ("service_description", models.TextField()),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "code_service",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("HAUTE", "Haute"),
                            ("BASSE", "Basse"),
                            ("NORMALE", "Normale"),
                        ],
                        null=True,
                    ),
                ),
                ("duree_estimee", models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Guichet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guichet_name", models.CharField(max_length=70, unique=True)),
                ("guichet_description", models.TextField()),
                (
                    "guichet_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouvert"),
                            ("BUSY", "Occupé"),
                            ("CLOSED", "Fermé"),
                            ("REPAIRING", "Maintenance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guichets",
                        to="api.agence",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(related_name="guichets", to="api.service"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "agent_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("BUSY", "Occupé"),
                            ("OFFLINE", "Hors ligne"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                ("phone", models.BigIntegerField(default=653658171)),
                ("born_date", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("ADMIN", "admin"), ("AGENT", "agent")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "guichet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="api.guichet",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id_ticket", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ticket_code",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "ticket_status",
                    models.CharField(
                        choices=[
                            ("WAITING", "En attente"),
                            ("CALLED", "Appelé"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("ABSENT", "Absent"),
                            ("TRANSFERRED", "Transféré"),
                            ("CANCELLED", "Annulé"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "called_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="called_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guichet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="api.guichet",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="api.client",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.service"
                    ),
                ),
            ],
        ),
    ]
