# Generated by Django 5.2.14 on 2026-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="matricule",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
