# Generated by Django 5.2.14 on 2026-07-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_description", models.TextField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_image", models.ImageField(upload_to="product_images/")),
                ("product_stock", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
