@host = http://127.0.0.1:8000
@refresh-token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDExMDkyNCwiaWF0IjoxNzg0MDI0NTI0LCJqdGkiOiI2NDE4ZTA3MDQ3M2U0ZWVkYTgxYTE3NmQ4OTRlM2E3NiIsInVzZXJfaWQiOiIxIn0.G9o5xqSJ-SVHnX9hkRjWSCBpWqchkYKgXLVYfJKvmTo",
 @access-token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0MDI5OTA2LCJpYXQiOjE3ODQwMjgxMDYsImp0aSI6ImI2NWVkODZmZTBhNzQ5YmI4Mjk2YmM3NDMzZTY1OTgyIiwidXNlcl9pZCI6IjEifQ.qHNi8MrcoslIK3pJLcz_iTZwnsWAphDFQbWiWbdIIMs
POST {{host}}/api/token/
Content-Type: application/json

{
    "username": "freddy",
    "password": "12345"
}

### test-get-token-autentikation

GET {{host}}/api/products/
Authorization: Bearer {{access-token}}

### test-post-token-autehntication

PUT {{host}}/api/products/tapioca
Authorization: Bearer {{access-token}}
Content-Type: application/json

{
    "product_name":"mandarine",
    "product_description":" this a product create by a {{access-token}} key",
    "product_price":1000.0,
}

